version: '3.7'

services:
  next:
    # env_file: .env
    build: 
      context: .
      dockerfile: ./compose/stage.Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./pages:/app/pages/
      - ./components:/app/components/
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "10"
