name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Build
        run: |
          npm deploy

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: out
          clean: true
          repository-name: "Lemon-Rocket/lecket-web-deploy"
